djangoProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(r'musicbutler/',include(('musicbutler.urls','musicbutler'),namespace='musicbutler')),
]

musicbutler/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import re_path as url

urlpatterns=[
    path('home',views.home),
    path('playlist',views.play_list),
    path('playlist/<int:playlist_id>/', views.playlist_song),
    path('<int:song_id>/',views.song),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('password-change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password-change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('register/', views.register, name='register'),
    path('<int:song_id>/comment/',views.song_comment, name='song_comment'),
    path('favouritelist/<int:user_id>/<int:list_id>/',views.favourite_list_song),
    path('<int:song_id>/add_favourite/',views.add_to_favorite,name='add_to_favorite'),
    path('Singer/',views.SingerInfo,name="SingerInfo"),#/Singer/
    path('CMS/',views.Chinese_MS,name = "Chinese_MS"),#/CMS/
    path('CFMS/',views.Chinese_FMS,name = "Chinese_FMS"),
    path('CB/', views.Chinese_BS, name="Chinese_BS"),
    path('WMS/', views.Western_MS, name="Western_MS"),
    path('WFS/', views.Western_FS, name="Western_FS"),
    path('Singer_detail/<int:singer_id>/',views.SingerDetail,name="SingerDetail"),
    path('read/', views.read, name='read'),
    path('read/singer',views.read_singer,name='read_singer'),
    path('delete/singer/<int:singer_id>/', views.delete_singer, name='delete_singer'),
    path('edit/singer/<int:id>/', views.edit_singer, name='edit_singer'),

    path('read/style', views.read_style, name='read_style'),
    path('add/style', views.add_style, name='add_style'),
    path('edit/style/<int:id>/', views.edit_style, name='edit_style'),
    path('delete/style/<int:style_id>/', views.delete_style, name='delete_style'),

    path('read/have', views.read_have, name='read_have'),
    path('add/have',views.add_have,name='add_have'),
    path('delete/style/<int:song_id> <int:playlist_id>',views.delete_have,name='delete_have'),
    path('read/playlist', views.read_playlist, name='read_playlist'),
    path('read/comment', views.read_comment, name='read_comment'),
    path('read/album', views.read_album, name='read_album'),
    path('delete/comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('delete/favouritelist/<int:list_id>/', views.delete_list, name='delete_list'),
    path('delete/album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('delete/list_song/<int:song_id>/<int:list_id>/', views.delete_list_song, name='delete_list_song'),
    path('add/', views.add, name='add'),
    path('add/singer',views.add_singer,name='add_singer'),
    path('delete/song/<int:song_id>/', views.dele, name='dele'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('add/playlist', views.add_playlist, name='add_playlist'),
    path('add/album', views.add_album, name='add_album'),
    path('delete/playlist/<int:list_id>/', views.delete_playlist, name='delete_playlist'),
    path('edit/playlist/<int:id>/', views.edit_playlist, name='edit_playlist'),
    path('edit/album/<int:id>/', views.edit_album, name='edit_album'),
    path('styles/', views.style_list, name = 'styles'),
    path('styles/<int:style_id>/songs/', views.songs_by_style, name='songs_by_style'),
    path('album/', views.album_list, name='album_list'),
    path('album/<int:album_id>/', views.album_detail, name='album_detail'),
    path('create/', views.create, name='create'),
]

templates/CMS.html
<head>
    <style>
        .guide {
            width: 95%;
            height: 40px;
            border-top: 4px black;
            border-bottom: 1px black;
            background-color: #545454;
            font-family: 'Ubuntu', serif;
        }
        .g {
            color:whitesmoke;
            list-style:none;
        }li{float:left}
        a{
            text-decoration: none;
        }
    </style>
</head>
{% extends "base.html" %}
 {% block title_block %}<title>Chinese Male Singer</title>{% endblock %}

{% block body_block %}
    <div class="guide">
    <ul class="g" {# style="text-align: center;" #}>
        <li><a href="http://127.0.0.1:8000/musicbutler/CMS/" style="color:whitesmoke">
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspChinese Male Singers&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a></li>
        <li><a href="http://127.0.0.1:8000/musicbutler/CFMS/" style="color:whitesmoke">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspChinese Female Singers&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a></li>
        <li><a href="http://127.0.0.1:8000/musicbutler/CB/" style="color:whitesmoke">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspChinese Bands&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a></li>
        <li><a href="http://127.0.0.1:8000/musicbutler/WMS/" style="color:whitesmoke">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspWestern Male Singers&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a></li>
        <li><a href="http://127.0.0.1:8000/musicbutler/WFS/" style="color:whitesmoke">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspWestern Female Singers&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a></li>
    </ul>
</div>
<br>
<h2>Chinese Male Singer</h2>
<br>
    <div class="product-list" id="main">
         {%  for item,item2 in ziplist%}
            <div style="width:25%" class="item1">
             <a href="/musicbutler/Singer_detail/{{ item.0 }}/">
                 <img src="{{ item.2 }}" height="150px" width="275px">
             </a>
                <p><a href="/musicbutler/Singer_detail/{{ item.0 }}/">{{ item2 }}</a></p>
            </div>
    {% endfor %}
{% endblock %}
 </div>
</div>
 </div>



templates/add_style.html
{% extends "base.html" %}
{% block title_block %}<title>add song</title>{% endblock %}
{% block body_block %}
<body>
    <center>
        <h1>Add Information</h1>
        <a href="{% url 'musicbutler:read_style' %}">Back</a>
        <table>
            <form action="{% url 'musicbutler:add_style' %}" method="post">
               {% csrf_token %}
                <tr>
                <td>
                    Name:
                </td>
                <td>
                    <input type="text" name="name">
                </td>
            </tr>

            <tr>
                <td align="center" colspan="2">
                    <input type="submit" value="add">
                    <input type="reset" value="reset">
                </td>
            </tr>
            </form>
        </table>
    </center>
</body>
{% endblock %}

templates/album_list.html
{% extends 'base.html' %}
{% block title_block %}<title>album list</title>{% endblock %}
{% block body_block %}
  <h1>Album List</h1>
  <table>
      <tr>
        <th>Name</th>
          <th>Photo</th>
      </tr>
        {% for album in page_obj %}
        <tr>
            <td><a href="{% url 'musicbutler:album_detail' album_id=album.album_id %}">{{ album.name }}</a><p>{{ album.song_num }} song(s) in total</p></td>

    <td><a href="{% url 'musicbutler:album_detail' album_id=album.album_id %}"><img src="{{ album.photo__link }}" alt="{{ album.name }}" width="150" height="150"><br></a></td>

        </tr>
        {% endfor %}
  </table>
  {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; First</a>
    <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; Previous</a>
  {% endif %}
  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <strong>{{ num }}</strong>
    {% else %}
      <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next &rsaquo;</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
  {% endif %}
  {% if albumlist %}
    <div class="album-container">
      {% for album in albumlist %}
        <div class="album">
          <a href="{{ album.get_absolute_url }}"><img src="{{ album.photo_link }}" alt="{{ album.name }}" width="200" height="100"></a>
          <h3><a href="{{ album.get_absolute_url }}">{{ album.name }}</a></h3>
        </div>
      {% endfor %}
    </div>
  {% endif %}
  {% if page_obj %}
    {{ page_obj }}
  {% endif %}
{% endblock %}


<style>
  .album-container {
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    margin-top: 20px;
  }
  .album {
    margin: 20px;
    text-align: center;
  }
</style>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block title_block %}<title>HomePage</title>{% endblock %}
    <link rel="stylesheet" type="text/css" href="main.css?v=<?php echo time(); ?>">
    <link rel="stylesheet" href="{% static 'bootstrap/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body style="background-color:#C0C0C0 ">
    {% include "header.html" %}
    <center>
        <div class="container pt-5">
            <div id="header">
                <h1 style="color:cornflowerblue;text-align:center;">Music Butler</h1>
            </div>
        </div>
        {% block body_block %}
            <h1>Welcome to our Homepage!</h1>
            <div class="container pt-5">
                <h2> Want to enjoy different kinds of music? Why not register to be our users now?</h2>
            </div>
            {% if query %}
                <h1>Songs called "{{ query }}"</h1>
                <h3>
                {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
                </h3>
            {% for song in results %}
            <h4>
                <a href="http://127.0.0.1:8000/musicbutler/{{ song.0 }}">{{ song.1 }}</a>
            </h4>
            {% empty %}
            <p>There are no results for your query.</p>
            {% endfor %}
                <p><a href="http://127.0.0.1:8000/musicbutler/home">Search again</a></p>
            {% else %}
                <h1>Search for songs</h1>
                <div class="container" style="display: inline-block;">
                <div class="row" style="display: inline-block;">
                    <form method="get">
                        {{ form.as_p }}
                    <input type="submit" value="Search">
                    </form>

        </div>
        </div>
        </div>
        {% endif %}

        {% endblock %}
    </center>
        <!-- include jquery.js and popper.js -->
        <script src="{% static 'jquery/jquery-3.5.1.js' %}"></script>
        <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
        <!-- import bootstrap js -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <footer>
            <div class="row">
                <div class="col-md-6">
                    <hr>
                    <p>Authors: lty, oyz, yyj, zmy</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <hr>
                    <p class="text-dark">Contact with us: 15868136503</p>
                    <p class="text-dark">Music Butler</p>
                </div>
            </div>
        </footer>

</body>

</html>

templates/edit_playlist.html
{% extends "base.html" %}
{% block title_block %}<title>edit playlist</title>{% endblock %}
{% block body_block %}
<body>
    <center>
        <h1>Edit Information</h1>
        <a href="{% url "musicbutler:read_playlist" %}">Back</a>
        <table>
            <form action="{% url 'musicbutler:edit_playlist' playlist.0 %}" method="post">
                {% csrf_token %}
            <tr>
                <td>
                    Name:
                </td>
                <td>
                    <input type="text" name="name", value="{{ playlist.1 }}">
                </td>
            </tr>
                <tr>
                    <td>
                    Photo_link
                </td>
                <td>
                    <input type="text" name="photo_link", value="{{ playlist.2 }}" >
                </td>
            </tr>
                <tr>
                    <td align="center" colspan="2">
                        <input type="submit" value="submit">
                        <input type="reset" value="reset">
                    </td>
                </tr>
            </form>
        </table>
    </center>
</body>
{% endblock %}

templates/edit_song.html
{% extends "base.html" %}
{% block title_block %}<title>edit song</title>{% endblock %}
{% block body_block %}
<body>
    <center>
        <h1>Edit Information</h1>
        <a href="{% url "musicbutler:read" %}">Back</a>
        <table>
            <form action="{% url 'musicbutler:edit' song.0 %}" method="post">
                {% csrf_token %}
            <tr>
                <td>
                    Name:
                </td>
                <td>
                    <input type="text" name="name", value="{{ song.1 }}">
                </td>
            </tr>
                <tr>
                    <td>
                    Photo_link
                </td>
                <td>
                    <input type="text" name="photo_link", value="{{ song.2 }}" >
                </td>
            </tr>
                <tr>
                <td>
                    Lyric:
                </td>
                <td>
                    <input type="text" name="lyric", value="{{ song.3 }}" >
                </td>
            </tr>
                <tr>
                <td>
                    Audio_link:
                </td>
                <td>
                    <input type="text" name="audio_link", value="{{ song.4 }}" >
                </td>
            </tr>
                <tr>
                <td>
                    Singer_id:
                </td>
                <td>
                    <input type="text" name="singer_id", value="{{ song.5 }}" >
                </td>
            </tr>
                <tr>
                <td>
                    Album_id:
                </td>
                <td>
                    <input type="text" name="album_id", value="{{ song.6 }}" >
                </td>
            </tr>
                <tr>
                <td>
                    Style_id:
                </td>
                <td>
                    <input type="text" name="style_id", value="{{ song.7 }}" >
                </td>
            </tr>
                <td align="center" colspan="2">
                    <input type="submit" value="submit">
                    <input type="reset" value="reset">
                </td>
            </tr>
            </form>
        </table>
    </center>
</body>
{% endblock %}

templates/edit_style.html
{% extends "base.html" %}
{% block title_block %}<title>edit style</title>{% endblock %}
{% block body_block %}
<body>
    <center>
        <h1>Edit Information</h1>
        <a href="{% url "musicbutler:read_style" %}">Back</a>
        <table>
            <form action="{% url 'musicbutler:edit_style' style.0 %}" method="post">
                {% csrf_token %}
            <tr>
                <td>
                    Name:
                </td>
                <td>
                    <input type="text" name="name", value="{{ style.1 }}">
                </td>
            </tr>


                <td align="center" colspan="2">
                    <input type="submit" value="submit">
                    <input type="reset" value="reset">
                </td>
            </tr>
            </form>
        </table>
    </center>
</body>
{% endblock %}w

templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-brand mb-0 h1"><img src="{% static 'logo.png' %}" height="50"></span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        {% if request.user.is_superuser %}
              <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/read">Song Management</a>
          {% else %}
        <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/home">Home <span class="sr-only">(current)</span></a>
        {% endif %}
      </li>
      <li class="nav-item">
          {% if request.user.is_superuser %}
              <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/read/singer">Singer Management</a>
          {% else %}
               <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/Singer">Singer</a>
          {% endif %}
      </li>
      <li class="nav-item">
          {% if request.user.is_superuser %}
              <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/read/album">Album Management</a>
          {% else %}
          <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/album">Album</a>
          {% endif %}
      </li>
      <li class="nav-item">
           {% if request.user.is_superuser %}
              <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/read/playlist">Playlist Management</a>
          {% else %}
        <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/playlist" >Playlist</a>
          {% endif %}
      </li>
     <li class="nav-item">
          {% if request.user.is_superuser %}
              <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/read/style">Style Management</a>
          {% else %}
        <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/styles" >Style</a>
         {% endif %}
      </li>
        <li class="nav-item">
            {% if request.user.is_superuser %}
              <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/read/comment">Comment Management</a>
          {% else %}
        <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/dashboard" >Dashboard</a>
            {% endif %}
      </li>
        <li class="nav-item">
            <span class="user">
            {% if request.user.is_authenticated %}
            Hello {{ request.user.first_name|default:request.user.username }},
            <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/logout">Logout</a>
            {% else %}
            <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/login">Log-in</a>
            {% endif %}
            </span>
        <li class="nav-item">
            {% if request.user.is_superuser %}
              <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/read/have">Songs of Playlist Management</a>
          {% else %}
        <a class="nav-link" href="http://127.0.0.1:8000/musicbutler/register">Sign up</a>
            {% endif %}
      </li>
      </li>
    </ul>
  </div>
</nav>

templates/info.html
{% extends "base.html" %}
{% block title_block %}<title>info</title>{% endblock %}
{% block body_block %}
    <strong style="font-size: 25px;">&nbsp{{ info }}</strong>
    <p>time spent: {{ time }} seconds</p>
    <p><a href="http://127.0.0.1:8000/musicbutler/read/{{ read_pos }}">Back</a></p>
{% endblock %}

templates/read.html
{% extends "base.html" %}
{% block title_block %}<title>read_song</title>{% endblock %}
{% block body_block %}
<body>
    <center>
    <a href="{% url 'musicbutler:add' %}">Add a Song</a>
        <table border="1" width="700">
            <tr>
                <th>Name</th>
                <th>Photo_link</th>
                <th>Lyric</th>
                <th>Audio_link</th>
                <th>Singer_id</th>
                <th>Album_id</th>
                <th>Style_id</th>
            </tr>
            {% for s in page %}
            <tr>
                <td>{{ s.1 }}</td>
                <td>{{ s.2 }}</td>
                <td>{{ s.3 }} </td>
                <td>{{ s.4 }}</td>
                <td>{{ s.5 }}</td>
                <td>{{ s.6 }}</td>
                <td>{{ s.7 }}</td>
                <td>
                    <a href="{% url 'musicbutler:edit' s.0%}">Edit</a>
                    <a href="{% url 'musicbutler:dele' s.0%}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </center>
{% endblock %}

templates/read_singer.html
{% extends "base.html" %}
{% block title_block %}<title>read_singer</title>{% endblock %}
{% block body_block %}
<body>
    <center>
    <a href="{% url 'musicbutler:add_singer' %}">Add a Singer</a>
        <table border="1" width="700">
            <tr>
                <th>Singer_ID</th>
                <th>Name</th>
                <th>Photo_link</th>
                <th>introduction</th>
            </tr>
            {% for k in page %}
            <tr>
                <td>{{ k.0 }}</td>
                <td>{{ k.1 }}</td>
                <td>{{ k.2 }}</td>
                <td>{{ k.3 }} </td>
                <td>
                    <a href="{% url 'musicbutler:edit_singer' k.0%}">Edit</a>
                    <a href="{% url 'musicbutler:delete_singer' k.0%}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </center>
{% endblock %}

templates/read_style.html
{% extends "base.html" %}
{% block title_block %}<title>read_style</title>{% endblock %}
{% block body_block %}
<body>
    <center>
    <a href="{% url 'musicbutler:add_style' %}">Add a New Style</a>
        <table border="1" width="700">
            <tr>
                <th>Style_ID</th>
                <th>Name</th>

            </tr>
            {% for m in page %}
            <tr>
                <td>{{ m.0 }}</td>
                <td>{{ m.1 }}</td>
                <td>
                    <a href="{% url 'musicbutler:edit_style' m.0%}">Edit</a>
                   <a href="{% url 'musicbutler:delete_style' m.0%}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </center>
{% endblock %}

templates/songs_by_style.html
<head>
    <title>Title</title>
    <style>
        table {
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            text-align: left;
        }
         th {
             background-color: #f2f2f2;
         }
    </style>
</head>
{% extends "base.html" %}
{% block title_block %}<title>style_name</title>{% endblock %}
{% block body_block %}
<body>
    <h1>Songs by Style: {{ style.name }}</h1>

    <table>
        <thead>
            <tr>
                <th>Number</th>
                <th>Song Name</th>
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
            {% for song in page %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="http://127.0.0.1:8000/musicbutler/{{ song.id }}/"> {{ song.name }}</td>
                    <td>
                        {% if song.image_url %}
                            <img src="{{ song.image_url }}" alt="Image" width="100">
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">No songs found for this style.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</body>
{% endblock %}

templates/style_list.html
{% extends "base.html" %}
{% block title_block %}<title>styles</title>{% endblock %}
{% block body_block %}
<head>
    <title>Style List</title>
    <style>
        ul{
            list-style:none;
        }
    </style>
</head>
<body>
    <h1>Style List</h1>

    <ul>
        {% for style in styles %}
            <li><a href="/musicbutler/styles/{{ style.id }}/songs/"> {{ style.name }} </a></li>
        {% endfor %}

    </ul>
</body>
{% endblock %}